export const PERMISSIONS = {
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_MASTER_DATA: 'MANAGE_MASTER_DATA',
  MANAGE_STUDENTS: 'MANAGE_STUDENTS',
  MANAGE_NOTEBOOK_TYPES: 'MANAGE_NOTEBOOK_TYPES',
  MANAGE_NOTEBOOK_REASONS: 'MANAGE_NOTEBOOK_REASONS',
  CREATE_NOTEBOOK_ISSUE: 'CREATE_NOTEBOOK_ISSUE',
  VIEW_NOTEBOOK_ISSUES: 'VIEW_NOTEBOOK_ISSUES',
  MANAGE_NOTEBOOK_STOCK: 'MANAGE_NOTEBOOK_STOCK',
  CREATE_PRINTLOG: 'CREATE_PRINTLOG',
  VIEW_PRINTLOGS: 'VIEW_PRINTLOGS',
  MANAGE_STOCK: 'MANAGE_STOCK',
  VIEW_REPORTS: 'VIEW_REPORTS',
  EXPORT_CSV: 'EXPORT_CSV',
  MANAGE_EMAIL_SETTINGS: 'MANAGE_EMAIL_SETTINGS'
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];